name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # 変更を監視するブランチを指定

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check if triggered by GitHub Actions bot
      run: |
        if [ "${{ github.actor }}" = "github-actions[bot]" ]; then
          echo "This run was triggered by the GitHub Actions bot, exiting."
          exit 1
        fi

    - name: Checkout repository
      uses: actions/checkout@v3  # リポジトリをチェックアウト
      with:
        fetch-depth: 0 
        token: ${{ secrets.GH_TOKEN }}


    - name: Set up Python
      uses: actions/setup-python@v4  # Pythonをセットアップ
      with:
        python-version: '3.11'  # Python 3.11を使用

    - name: Upgrade pip
      run: python -m pip install --upgrade pip  # pipをアップグレード

    - name: Install dependencies
      run: pip install -U sphinx sphinx-rtd-theme sphinx_fontawesome myst_parser opencv-python numpy cython # 依存関係をインストール

    - name: Build Python extensions
      run: python setup.py build_ext --inplace  # Python拡張機能をビルド

    - name: Build Sphinx documentation
      run: sphinx-build -b html ./docs/script ./docs  # Sphinxドキュメントをビルド

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        if [ "$(git diff --shortstat)" != "" ]; then
          git add .
          git commit -m "GitHub Actions: Build and deploy Sphinx docs"
          git push origin HEAD:${GITHUB_REF}
        fi
